travis:
  secure:
    BINSTAR_TOKEN: L/es7Kyub3JxYmDGMWJOGYlXfBMeiHASap3MwQWjX2XhjWsALLyZRaNo1mXP3fI4Br7m7AaE9R2pqy3us7+ttGMpCvBlZuAzYpwlxLeAi+xMeTRIp/4hsKJ+Y9vAchBlN6+jOXPgAjrQ05Myak3WlXTKCkHTiU8YThJiJhSUVk0r3QldRqgeWuAWDH5JEE5LQVXfmExJSf+woWgML+tSPTTwSB87EK+9QhpO3pFmLqL9z1QK9o3SdDYOhUfzC1tTC7pgMY8AGFMgpYyx33daY/Do1mLixG3+RRCMQLNqRMOr3kmzFPwnrWfVQtzrBXOR823o9vheV4Gj/QMpe8fSzlFyKt1MFHTgwtBTMa3KZbMIadQcn5pSfGz06VRAKcojagaKvDmxytCSnW8MsV2zmWiOABydFmRKkYFsbH9VJkm53HxXCnV7ZL2uIRalv6GVK1flxbpsW4ywttFZHxZCiCqH0cq9VBKKd0/3Uy8T0Gvpv02sLWpdhAjYzaIrZk6y9SQrisB5DDFXKY46Anj+HJRqmcsB9VgAD6NCVlCkV0Naw5FVFlbKXxy8nPyLVDZ4v+jwUlrPcLULVOqqWXrCbks/QjZb+CcJRIxDNC/ey7se+ULWiEuqJPLrynyPtmC8ReSBGHyEMpnPZ88oe42TjpnB9uKVRCWwPt917bLO7mc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
